### ISSUE TITLE
Uncaught exception when ECGmd powered off

### ISSUE THREAD

**Issue by Appappa** [ShimmerEngineering/Shimmer-C-API#10]
There is an uncaught exception on the ShimmerBluetooth.cs ReadData thread in the following circumstances :

With ECGmd in state SHIMMER_STATE_CONNECTED and a start streaming request sent, power off the ECGmd
In ReadData an exception is raised and caught (line 1507 of ShimmerBluetooth.cs)
causing ReadBattery to be called (line 1532)
causing WriteBytes to be called (line 4809)
causing SerailPort.Write to be called (line 59 of ShimmerLogAndStreamSystemSerialPort.cs)
causing an uncaught Timeout exception

**Comment by JongChern** [comment]
Hi, thanks for the feedback.

The exception is caught and acted upon in ShimmerBluetooth.cs (_see code snipper below_) 

Are you facing any difficulties due to this?

```c#
catch (System.TimeoutException)
                {
                    //
                    if (ShimmerState == SHIMMER_STATE_STREAMING || ShimmerState == SHIMMER_STATE_CONNECTED)
                    {
                        //System.Console.WriteLine("Timeout Streaming");
                        StreamTimeOutCount++;
                        if (StreamTimeOutCount % 5 == 0 && ShimmerState == SHIMMER_STATE_CONNECTED && GetFirmwareIdentifier() == FW_IDENTIFIER_LOGANDSTREAM)
                        {
                            System.Console.WriteLine("Sending Get Status Command");
                            WriteBytes(new byte[1] { (byte)ShimmerBluetooth.PacketTypeShimmer3SDBT.GET_STATUS_COMMAND }, 0, 1);
                            System.Threading.Thread.Sleep(500);
                        }
                        if (StreamTimeOutCount > 10)
                        {
                            CustomEventArgs newEventArgs = new CustomEventArgs((int)ShimmerIdentifier.MSG_IDENTIFIER_NOTIFICATION_MESSAGE, "Connection lost" );
                            OnNewEvent(newEventArgs);
                            Disconnect();
                        }
                        if(GetFirmwareIdentifier() == FW_IDENTIFIER_BTSTREAM && ShimmerState == SHIMMER_STATE_CONNECTED)
                        {
                            StreamTimeOutCount = 0;
                        }
                        if (GetFirmwareIdentifier() == FW_IDENTIFIER_SHIMMERECGMD && ShimmerState == SHIMMER_STATE_CONNECTED)
                        {
                            ReadBattery();
                        }
                    }

                }
```

**Comment by Appappa** [comment]
Hi, the exception is being raised as a result of the ReadBattery function call inside the catch block. So yes the first exception is being handled but the subsequent exception (as a result of ReadBattery) is not being handled.

**Comment by JongChern** [comment]
sorry , i get it now, we will make the following update
```c#
                            try
                            {
                                ReadBattery();
                            }
                            catch (System.TimeoutException)
                            {
                                Disconnect();
                            }
```

**Comment by Appappa** [comment]
Thanks. 

Maybe also consider protecting the line 

    WriteBytes(new byte[1] { (byte)ShimmerBluetooth.PacketTypeShimmer3SDBT.GET_STATUS_COMMAND }, 0, 1);

which is a few lines above the ReadBattery() call, since it is ultimately a serial port write timeout that is occurring.

**Comment by JongChern** [comment]
noted with thanks
