### ISSUE TITLE
Linux build instructions

### ISSUE THREAD

**Issue by sedurCode** [ShimmerEngineering/Shimmer-C-API#16]
Hi,
I am trying to build the API in an Ubuntu VM, but it is not clear where I am meant to change the .NET version, or indeed how I am meant to find and install the dependencies of the project in order to build the API (and eventually shimmer connect).

If you could please provide more detailed instructions, it would be greatly appreciated. 

Many Thanks

**Comment by JongChern** [comment]
Hi Unfortunately we only provide instructions on how to use the application on Ubuntu. https://github.com/ShimmerEngineering/Shimmer-C-API/wiki/Running-Shimmer-Capture-on-Linux-(Ubuntu)
