### ISSUE TITLE
Garbage Data when getting closer to bandwidth limit

### ISSUE THREAD

**Issue by HeyFlash** [ShimmerEngineering/Shimmer-C-API#17]
It seems to me that the C# API is not working correctly when there the data being transferred is getting closer to or exceeding the bluetooth bandwidth limit.

The desired behaviour would be that data is being dropped, but the data that arrives is still correct. However, currently the data that arrives is unusable, sometimes even the timestamp data will no longer be an increasing value, but just random noise instead. It seems that this is the result of data misalignment, as sometimes e.g. the ppg data will appear (at least partially) in another column.
When this behaviour occurs and "Time Stamp Alignment Check" is activated, "Misaligned Byte Stream" will be written to the console, however, it is unclear to me how to handle this situation when coding against the C# API, especially as the Consensys App shows that it should be possible to just drop data and still receive the correct data.

I have attacked four screenshots, two of Consensys, two of ShimmerCapture. The two with the same frequency have both been taken immediately after each other, without changing the shimmer settings. 

In the 256Hz case, Consensys reports 100% package reception rate and the data is correct, while in ShimmerCapture there is already some garbage:
![Consensys_256Hz](https://user-images.githubusercontent.com/10146895/70609185-aced4f80-1c01-11ea-89be-2277d73ebd1e.png)
![ShimmerCapture_256Hz](https://user-images.githubusercontent.com/10146895/70609184-ac54b900-1c01-11ea-9260-fecb7df1b72d.png)

In the 1024Hz case, Consensys reports 25% package reception rate, but the data is still correct, while in ShimmerCapture there is only garbage:

![Consensys_1024Hz](https://user-images.githubusercontent.com/10146895/70609183-ac54b900-1c01-11ea-89a4-292dce3abb31.png)
![ShimmerCapture_1024Hz](https://user-images.githubusercontent.com/10146895/70609182-ac54b900-1c01-11ea-9823-658aeab7da9e.png)

If I reduce the transferred data even more, e.g. by disabling everything except the PPG sensor, the data arrives correctly in ShimmerCapture.

**Comment by JongChern** [comment]
Hi,

There is an option on the ShimmerCapture UI interface to check the time stamp alignments, this should mitigate the issue you are seeing:-
![image](https://user-images.githubusercontent.com/2862032/70681143-56514580-1cd5-11ea-9055-d0ea5e56e475.png)

For further explanation please refer to:-
https://github.com/ShimmerEngineering/Shimmer-C-API/wiki/Effect-of-Bluetooth-Transmission-Loss-to-the-Byte-Stream

**Comment by HeyFlash** [comment]
Hi,

thank you for the explanation. However, this only improves the situation a little bit in that it really does ensure that no garbage data is being written. However, it also results in no data arriving at all even if I am well below the theoretical bandwidth limit (as per Consensys).

I.e. in both the cases represented above I will not receive any data via the C#-API, when the time stamp alignment check is activated. Only if I drop the number of channels and the frequency so that the required bytes amount to less than 20% of the bandwidth limit, will I receive any data.

Consensys, on the other hand has no trouble receiving correct data, even if the settings exceed the theoretical bandwidth limit. Why is it possible for Consensys to achieve this, but not for the C#-API?

**Comment by JongChern** [comment]
C# API, was fundamentally designed to work in optimum settings (i.e. without high packet loss). Hence we recommend users pick an optimum setting. For example rather than setting the device to sample at 2048Hz while losing 50% of packets, we would recommend using 1024 Hz. I think in most cases it would be better to use 1024Hz anyway (rather than have 50% packet loss) because that would at least make the intervals between your samples consistent.

**Comment by HeyFlash** [comment]
OK, I have now found a somewhat consistent way of giving feedback to the user. Any setting that is above 40% of the theoretical bandwidth limit will result in too much package loss and thus in no received data.

Big part of my trouble was that in my own program the function ShimmerBluetooth.packetTimeStampChecker was using an incorrect value for ADCRawSamplingRateValue.
This happens because the function "InterpretInquiryResponseShimmer3" is not called when "WriteSamplingRate" is called, and thus the real sampling rate and the ADCRawSamplingRateValue are out of sync and thus the upperLimit and lowerLimit of the packetTimeStampChecker are incorrect.

I now make sure to call "WriteSensors" after calling "WriteSamplingRate", which will ensure that the ADCRawSmaplingRateValue is correct. There is a very subtle hint in the ShimmerCapture source code that this is probably what should be done:
`EnableSensors();    //Called last`
But it was not clear to me that "called last" was not just a statement of fact, but a "you must call this last, otherwise it won't work.

Anyway, I don't know if this behaviour is a bug in the API or by design, if the latter, it should probably be made more explicit. I'm writing this mainly for the benefit of anyone who might have similar problems. This information should probably also be added to the wiki page you provided.

**Comment by JongChern** [comment]
Thanks for the feedback, we are always looking to improve, I will keep this issue open until the subject matter you've mentioned above has been addressed.

**Comment by JongChern** [comment]
I've added a page regarding using writesensors prior to starting a bluetooth stream.

https://github.com/ShimmerEngineering/Shimmer-C-API/wiki/Recommended-Communication-Flow
