### ISSUE TITLE
No data return for ShimmerECGConsoleAppExample 

### ISSUE THREAD

**Issue by ronnie-uq** [ShimmerEngineering/Shimmer-C-API#18]
Hi,

I'm using the ShimmerECGConsoleAppExample to streamming data from Shimmer sensor via C# API.

However, it does not return data.

SensorData data = objectCluster.GetData(Shimmer3Configuration.SignalNames.ECG_LA_RA, "CAL");

data is null.

Wondering if there is any user manual or document for C#API that guide me on how to use this API for ECG ? 

If I use Consensys to steam data , it is ok and working with Shimmer sensor.

Thanks

**Comment by JongChern** [comment]
Hi what do you see on the console prints? is the csv file being generated by the example?

**Comment by ronnie-uq** [comment]
I have not use log yet, I was trying to get streaming working and return data to the objectCluster, but it does not return raw data for "ECG_LA_RA" signal. 

Sensor data variable from objectCluster is null. What could possible that I'm missing here?

Console output:
Connecting
ShimmerID1 State = Connecting

ShimmerID1 State = Connected

Connected
ShimmerID1 State = Streaming

data is null

ShimmerID1 State = Connected

Connected
ShimmerID1 State = None

Disconnected
The thread 0x459b4ab0 has exited with code 0 (0x0)
The thread 0x459b4980 has exited with code 0( 0x0)



however , if I set the config to SENSOR_A_ACCEL then I could get return data LOW_NOISE_ACCELEROMETER_X.

**Comment by ronnie-uq** [comment]
It failed before it writes data into csv file. Please see my output above

**Comment by JongChern** [comment]
I can confirm that the example is working, my console prints are very different from yours

Hello
Connecting
Status Response Received
Connected


EXG CONFIGURATION SET USING SHIMMER CONSTRUCTOR
EXG CHIP 1 CONFIGURATION
3 160 16 64 64 45 0 0 2 3
EXG CHIP 2 CONFIGURATION
3 160 16 64 71 0 0 0 2 1

EXG CONFIGURATION AFTER MANUALLY SETTING THE VALUES (RATE and GAIN)
EXG CHIP 1 CONFIGURATION
4 160 16 80 80 45 0 0 2 3
EXG CHIP 2 CONFIGURATION
4 160 16 80 87 0 0 0 2 1

SET DEFAULT ECG CONFIGURATIONS AGAIN
EXG CHIP 1 CONFIGURATION
0 160 16 64 64 45 0 0 2 3
EXG CHIP 2 CONFIGURATION
0 160 16 64 71 0 0 0 2 1

SET ECG DATA RATE AUTOMATICALLY BY CHANGING THE SAMPLING RATE OF THE SHIMMER
EXG CHIP 1 CONFIGURATION
3 160 16 64 64 45 0 0 2 3
EXG CHIP 2 CONFIGURATION
3 160 16 64 71 0 0 0 2 1

IN ABOUT 5 SECONDS STREAMING WILL START AFTER THE BEEP
Sending Get Status Command
Streaming
Data being written to ecg.csv
ACK for Streaming Command Received

are you using https://github.com/ShimmerEngineering/Shimmer-C-API/tree/master/ShimmerECGConsoleAppExample ?

**Comment by ronnie-uq** [comment]
Yes, I'm using that example.

Do I need to modify anything from the example code other than bluetooth com port?

Seems some part of the example code are not necessary like read EXG CHIP 1 CONFIGURATION?

**Comment by JongChern** [comment]
you only need to modify the comport nothing else.

**Comment by ronnie-uq** [comment]
New output like below, seems like it only got one line of data , and ecg.csv file is empty , 0 bytes ,but it is locked.

ShimmerID1 State = Connecting

Connecting

ShimmerID1 State = Connected

Connected




EXG CONFIGURATION SET USING SHIMMER CONSTRUCTOR

EXG CHIP 1 CONFIGURATION

3 
168 
16 
64 
64 
45 
0 
0 
2 
3 

EXG CHIP 2 CONFIGURATION

3 
160 
16 
64 
71 
0 
0 
0 
2 
1 



EXG CONFIGURATION AFTER MANUALLY SETTING THE VALUES (RATE and GAIN)

EXG CHIP 1 CONFIGURATION

4 
168 
16 
80 
80 
45 
0 
0 
2 
3 

EXG CHIP 2 CONFIGURATION

4 
160 
16 
80 
87 
0 
0 
0 
2 
1 



SET DEFAULT ECG CONFIGURATIONS AGAIN

EXG CHIP 1 CONFIGURATION

0 
168 
16 
64 
64 
45 
0 
0 
2 
3 

EXG CHIP 2 CONFIGURATION

0 
160 
16 
64 
71 
0 
0 
0 
2 
1 



SET ECG DATA RATE AUTOMATICALLY BY CHANGING THE SAMPLING RATE OF THE SHIMMER

EXG CHIP 1 CONFIGURATION

3 
168 
16 
64 
64 
45 
0 
0 
2 
3 

EXG CHIP 2 CONFIGURATION

3 
160 
16 
64 
71 
0 
0 
0 
2 
1 



IN ABOUT 5 SECONDS STREAMING WILL START AFTER THE BEEP

ShimmerID1 State = Streaming

Streaming

Data being written to ecg.csv

data is not null
80.5361313266911,

The thread 0x42f53850 has exited with code 0 (0x0).

**Comment by ronnie-uq** [comment]
It is working now, however csv writing is still not working, it will terminate thread. 

another question about IBI algorithm
ECG to Heart Rate/Inter Beat Interval(IBI) algorithm
PPG to Heart Rate/Inter Beat Interval(IBI) algorithm
Is there any description about these algorithm , how to use them in example code?

Thanks

**Comment by ronnie-uq** [comment]
It is working now , I guess this issue could be closed. Thanks for the help.
