### ISSUE TITLE
Run the code and start Shimmer Device

### ISSUE THREAD

**Issue by gdidelot** [ShimmerEngineering/Shimmer-C-API#6]
Run the code and switch on the Shimmer Device => no connection event fired ( MSG_IDENTIFIER_STATE_CHANGE )

**Comment by ShimmerEngineering** [comment]
I think there is a misunderstanding , the code does not automatically connect to a Shimmer device whenever the Shimmer device is switched on. You have to explicitly call the connect method when you want to connect to a shimmer device. e.g. for a successful connection switch on the device first and then call the connect method.
