### ISSUE TITLE
Connect / Disconnect

### ISSUE THREAD

**Issue by gdidelot** [ShimmerEngineering/Shimmer-C-API#8]
C# Unit test with Rev 0.7

I have the following C# unit test :

ISorinShimmerEcg sorinShimmerEcg = new SorinShimmerEcg();
sorinShimmerEcg.StartStreaming(ShimmerTest.Channels, (ulong)(ShimmerTest.Rate * ShimmerTest.BufferSizeInSec * 4 * ShimmerTest.Channels), 4 * ShimmerTest.Rate);

Thread.Sleep(20000);

Assert.IsTrue(sorinShimmerEcg.IsConnected);

sorinShimmerEcg.StopStreaming();

The Rate is 50, the BufferSizeInSec is 60, th Channels is 2.

On test execution , I have the state Connecting and Connected and Streaming.
When the code run the line sorinShimmerEcg.StopStreaming(); sometimes the application crash on your file Shimmer32Feet.cs on line 94 : 

protected override void WriteBytes(byte[] b, int index, int length)
{
    peerStream.Write(b, index, length);
}

The method to stop the streaming is :

1° I call the Shimmer32Feet method StopStreaming()
2° I call the Shimmer32Feet method Disconnect()

I think this class have to be disposable in order to destroy properly the peerStream variable and it must have a try catch block.

Regards
Didelot Guillaume

**Comment by JongChern** [comment]
hi we've managed to replicate the issue, do to an uncaught exception, we will push out a fix by next week.
