### ISSUE TITLE
EXG2_24BIT Status

### ISSUE THREAD

**Issue by Appappa** [ShimmerEngineering/Shimmer-C-API#9]
Is there a reason that for 24bit EXG2 the Status signal name is "EXG2 Sta" and not SignalNames.EXG2_STATUS. 

See line 3075 of ShimmerBluetooth.cs

**Comment by ShimmerEngineering** [comment]
Hi, there is no reason. It is probably something we missed when making the update to using SignalNames.X . Will make the update. Thanks for the feedback!
